### ISSUE TITLE
Beta3 should use postprocessing block on AGP 3

### ISSUE THREAD

**Issue by hzsweers** [bugsnag/bugsnag-android-gradle-plugin#55] opened 2017-10-16 07:39 UTC
I have a block like this in my build.gradle

```gradle
release {
  signingConfig signingConfigs.release
  postprocessing.proguardFiles = ['proguard-rules.pro']
  postprocessing.optimizeCode = true
  postprocessing.obfuscate = false
}
```

But the script fails with the following trace

```
Caused by: org.gradle.api.GradleException: The `proguardFiles` method cannot be used with together with the `postprocessing` block.
        at com.android.build.gradle.internal.ExtraModelInfo.handleIssue(ExtraModelInfo.java:118)
        at com.android.builder.core.ErrorReporter.handleSyncError(ErrorReporter.java:77)
        at com.android.build.gradle.internal.dsl.BuildType.checkPostprocessingConfiguration(BuildType.java:703)
        at com.android.build.gradle.internal.dsl.BuildType.proguardFiles(BuildType.java:364)
        at com.bugsnag.android.gradle.BugsnagProguardConfigTask.createProguardConfig(BugsnagProguardConfigTask.groovy:49)
```

It looks like the plugin is trying to add a file or reading from the old format and should use `postprocessing` instead

**Comment by fractalwrench** [comment] 2017-10-16 13:37
Thanks for the report @hzsweers - I've confirmed that I can reproduce the issue with your example project. 

I was curious what the benefit of using `postprocessing` is over the current [proguard docs](https://developer.android.com/studio/build/shrink-code.html#gradle-shrinker). Are more options available for proguard, or is it simply the new syntax for AGP 3? I couldn't find any documentation for the `postprocessing` task - is it a public API? 

Our plugin automatically adds its own proguard config - an immediate workaround would be to [add this in manually](https://docs.bugsnag.com/platforms/android/sdk/mapping/#automatic-proguard-config). I was able to generate a signed APK using your example project with this solutionl

**Comment by hzsweers** [comment] 2017-10-16 18:56
Yeah I think it's just the new API, less proguard specific and preparing for R8. I'll try that, thanks!

**Comment by hzsweers** [comment] 2017-10-17 04:40
yep looks like that worked fine, thanks! Do you want me to leave this open for the longer term `postprocessing` or close it out?

**Comment by fractalwrench** [comment] 2017-10-23 08:23
Thanks @hzsweers - it'd be good to leave this one open as we'll eventually want to move over to using the new API, or find a way of supporting both at the same time.

**Comment by fractalwrench** [comment] 2018-01-23 09:10
@hzsweers from the response on [this issue](https://issuetracker.google.com/issues/70522935) it appears that `postprocessing` is internal and not intended for direct use. If the public API changes with R8 then we'll alter the plugin to handle that, but for now I think it'd be best to close this issue.

**Closed by fractalwrench** 2018-01-23 09:10 UTC
Labels: enhancement
