### ISSUE TITLE
7.4.1 uploadJvmMappings option causes dexguard build failure

### ISSUE THREAD

**Issue by SeoJungHong** [bugsnag/bugsnag-android-gradle-plugin#508] opened 2023-03-01 13:14 UTC
### Description
Hello. I'm using dexguard for release builds. It's been working fine for the past few months without any issues.
Also, in the app's build.gradle file, I have set as below to upload the mapping file.

```groovy
bugsnag {
    uploadJvmMappings = true
    uploadNdkMappings = false
    failOnUploadError = false
}
```

### Error Message
As described in the docs, we set the plugin version as below
```groovy
buildscript {
    dependencies {
        // ...
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:7.+"
    }
}
```
So it seems that  from last week plugin 7.4.1 was applied automatically.
Since then, the dexguard release app build task failed with the error message below.

```
* What went wrong:
A problem occurred configuring project ':app-tossplace'.
> Task with name 'dexguardAabRelease' not found in project ':app-tossplace'.
```

### Environment
* Android Studio version: Chipmunk 2021.2.1 Patch 2
* Gradle version: 7.4.2
* Android Gradle Plugin (AGP) version: 7.2.1
* Bugsnag Android Gradle Plugin version: 7.4.1
* Bugsnag manifest section (if modified):

**Comment by tomlongridge** [comment] 2023-03-01 18:14
@SeoJungHong - we would expect there to be a task with the name `dexguardAabRelease` if you have DexGuard enabled. In 7.4.1 we fixed an issue ([#496]) where the task name wasn't getting set correctly, so I'm not sure why it would now cause issues for you.

What version of DexGuard do you have?

Also, in the issue title you say "uploadNdkMappings" causes the issue, but that appears to be an unrelated option which you have disabled. Is that a typo or do you suspect it is this option causing it?

**Comment by SeoJungHong** [comment] 2023-03-02 01:41
The version of Dexguard is 9.3.15
Sorry it's just a typo.. I fixed the title!

**Comment by mclack** [comment] 2023-03-03 13:46
Hi @SeoJungHong - we're keen to reproduce the error you are seeing but we haven't been able to do it so far. Would it be possible for you to share your `build.gradle` files with us and also let us know what command you are using for your build?

If you’d rather not share the files over here which will be publicly accessible, then you can write into us at [support@bugsnag.com](mailto:support@bugsnag.com) and attach the files there instead.

**Comment by johnkiely1** [comment] 2023-04-13 08:39
Hi @SeoJungHong, going to close this out as we have not heard from you and we have been unable to reproduce. Feel free to send us your build.gradle files via [support@bugsnag.com](mailto:support@bugsnag.com) and we can continue investigating in a support ticket.

**Comment by SeoJungHong** [comment] 2023-04-24 03:54
Sorry for such a late reply.. I couldn't possibly check this thread due to a large workload recently.

### build.gradle file
Project root build.gradle
```groovy
buildscript {
    dependencies {
        // ...
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:7.+"
    }
}
```

app module build.gradle

```groovy
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id "kotlin-kapt"
    id "org.jetbrains.kotlin.plugin.serialization" version "$kotlin_version"
    id "io.gitlab.arturbosch.detekt" version "$detekt_version"
    id "androidx.navigation.safeargs.kotlin"
    id "com.bugsnag.android.gradle"
}

apply from: './app-version.gradle'
apply from: './dexguard.gradle'

bugsnag {
    uploadJvmMappings = true
}

android {
    compileSdkVersion rootProject.ext.compile_sdk

    defaultConfig {
        applicationId "com.tossplace.app"
        minSdkVersion rootProject.ext.min_sdk
        targetSdkVersion rootProject.ext.target_sdk
        versionCode tossPlaceAppVersionCode
        versionName tossPlaceAppVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "$compose_compiler"
    }
    lintOptions {
        abortOnError false
    }
    signingConfigs {
        debug {
            storeFile rootProject.file('keys/debug.keystore')
        }
        release {
            storeFile rootProject.file('keys/release.keystore')
            storePassword BuildEnv['TOSSPLACE_KEY_PASSWORD']
            keyAlias BuildEnv['TOSSPLACE_KEY_ALIAS']
            keyPassword BuildEnv['TOSSPLACE_KEY_PASSWORD']
        }
    }

    packagingOptions {
        jniLibs.useLegacyPackaging true
        exclude 'META-INF/*'
    }

    buildTypes {
        debug {
            minifyEnabled false
            applicationIdSuffix ".debug"
        }
        release {
            minifyEnabled true
            shrinkResources false
            debuggable false
            signingConfig signingConfigs.release
            applicationIdSuffix ".release"
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "app-tossplace-${variant.name}-${variant.versionName}.apk"
        }
    }
}

dependencies {
    // ... internal modules omitted
    implementation "com.bugsnag:bugsnag-android:5.28.4"
}
```

### Command 

```
app-tossplace:assembleRelease
```

### Additional 

Even though we update to the 7.5.0 version, the situation is the same.
dexguardVersion=9.3.15
dexguardGradlePluginVersion=1.3.15

**Comment by SeoJungHong** [comment] 2023-04-24 04:01
Oh I think I figured it out.
Since we don't use any flavors

**Comment by johnkiely1** [comment] 2023-05-16 10:06
HI @SeoJungHong, apologies for the delay here. I've been trying to reproduce what you are seeing but have not had any success doing it. Would you be able to provide a cut down reproduction example project that demonstrates this? 

I'm particularly curious around how you have initialised Dexguard?  Setting `minifyEnabled = true` would be unusual and not the way Dexguard would expect. Additionally I would have expected a Dexguard configuration block in you `build.gradle` file.

**Comment by johnkiely1** [comment] 2023-06-05 10:03
Going to close this out as we have been unable to reproduce the exact issue you are seeing. Happy to reopen if you can give us some more information. 

We have also introduced a new mechanism for uploading mapping files as documented here: https://docs.bugsnag.com/platforms/android/showing-full-stacktraces/#using-the-bugsnag-cli

This may provide an additional workaround for you.

**Closed by johnkiely1** 2023-06-05 10:03 UTC
Labels: awaiting feedback
