### ISSUE TITLE
Not able to upgrade from 4.7.5 to 5.0.0

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [bugsnag/bugsnag-android-gradle-plugin#280] opened 2020-08-21 18:55 UTC
### Expected behavior
Be able to run the project using Bugsnag AGP 5.0.0 via Android Studio.

### Observed behavior
I'm on 4.7.5 trying to upgrade to 5.0.0 following [the guide](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/master/UPGRADING.md), but I can't run the project via Android Studio.

#### Android Studio

Gradle Sync Warning

![image](https://user-images.githubusercontent.com/45950956/90924247-7b9a6580-e3c5-11ea-846b-6e9f35e7fe83.png)

Build error
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not create task ':app:bugsnagReleaseBetaTask'.
> Could not create task of type 'BugsnagReleasesTaskGradle6Plus'.
   > Could not generate a decorated class for type BugsnagReleasesTaskGradle6Plus.
      > retrofit2/Response
```

![image](https://user-images.githubusercontent.com/45950956/90924771-6e31ab00-e3c6-11ea-9d02-775cc0f39be7.png)

### Steps to reproduce
Just update the plugin to `5.0.0`

### Version
Bugsnag 5.0.1
Bugsnag AGP 5.0.0

### Additional information
Android Studio 4.0.1
AGP 4.0.1
Kotlin 1.4.0
Gradle 6.6
JDK 8

I'm able to build the project through command line: `./gradlew clean app:assembleDebug`.

**Comment by phillipsam** [comment] 2020-08-24 12:13
Hi @guilherme-pereira-ifood Thanks for the report! It looks like there is an issue in how the new version is published to jcenter. We are investigating a fix for this issue.
In the meantime, you should find this works if you use `mavenCentral` ahead of `jcenter` in your project's repository settings.

**Comment by guilherme-pereira-ifood** [comment] 2020-08-24 12:21
@phillipsam in fact I don't even have `mavenCentral` declared on my repository settings. I think I'll wait for the `jcenter` fix. Thank you!

**Comment by tomlongridge** [comment] 2020-08-24 17:20
The artefact is now correctly published on `jcenter` - you may need to clear your caches to get the updated pom.

**Comment by guilherme-pereira-ifood** [comment] 2020-08-25 13:33
@tomlongridge we still see the warnings on every sync. Do you think I should open a new issue for that?

**Comment by guilherme-pereira-ifood** [comment] 2020-08-25 13:53
@tomlongridge even after: `rm -rf ~/.gradle/caches/build-cache-1/ && rm -rf ~/.gradle/caches/transforms-2/`,  `./gradlew clean cleanBuildCache` I wasn't able to build the project through Android Studio.

Is there any other cache I need to clean?

**Comment by hijamoya** [comment] 2020-08-25 13:58
@tomlongridge the issue still exists

**Comment by guilherme-pereira-ifood** [comment] 2020-08-25 14:33
@hijamoya I managed to make it work. Just run the `Refresh Gradle Dependencies` and you'll be good to go:

![image](https://user-images.githubusercontent.com/45950956/91186281-3f1c8180-e6c5-11ea-8cf8-5d785ebdafd0.png)

**Comment by tomlongridge** [comment] 2020-08-25 14:36
Thanks @guilherme-pereira-ifood - was about to post the same (`./gradlew build --refresh-dependencies`).

**Comment by guilherme-pereira-ifood** [comment] 2020-08-25 20:03
@tomlongridge this solved the issue when running `./gradlew app:assembleDebug`, but now I'm trying to run `./gradlew app:assembleRelease` and now I have another issue:

```
> Task :app:processBugsnagReleaseManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processBugsnagReleaseManifest'.
> okio.Okio.sink$default(Ljava/io/File;ZILjava/lang/Object;)Lokio/Sink;
```

I also tried to run `./gradlew app:assembleRelease --refresh-dependencies`

**Comment by tomlongridge** [comment] 2020-08-26 08:46
@guilherme-pereira-ifood - would you mind running it with the `--stacktrace` and `--debug` options so we can get some more informative output?

Also, we should be releasing 5.0.1 later today, so it might be worth waiting for this as it seems like it might be related to a cached dependency on your system with v5.0.0.

**Comment by tomlongridge** [comment] 2020-08-26 11:00
Further to this [5.0.1](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v5.0.1) is now released.

**Comment by guilherme-pereira-ifood** [comment] 2020-08-26 16:10
@tomlongridge even after upgrading to `5.0.1` I still face the same issue. Here's the execution with `--stacktrace`:

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processBugsnagReleaseManifest'.
> okio.Okio.sink$default(Ljava/io/File;ZILjava/lang/Object;)Lokio/Sink;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processBugsnagReleaseManifest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.NoSuchMethodError: okio.Okio.sink$default(Ljava/io/File;ZILjava/lang/Object;)Lokio/Sink;
        at com.bugsnag.android.gradle.AndroidManifestInfo.write$bugsnag_android_gradle_plugin(AndroidManifestInfo.kt:19)
        at com.bugsnag.android.gradle.BaseBugsnagManifestUuidTask.writeManifestInfo(BugsnagManifestUuidTask.kt:37)
        at com.bugsnag.android.gradle.BugsnagManifestUuidTask.updateManifest(BugsnagManifestUuidTask.kt:76)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:570)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:555)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:538)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:279)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:268)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:195)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

**Comment by guilherme-pereira-ifood** [comment] 2020-08-26 17:21
I have deleted the `~/.gradle/caches/` folder and still no success.

**Comment by mattdyoung** [comment] 2020-08-27 10:29
Hi @guilherme-pereira-ifood 

We haven't been able to reproduce the issue you're seeing. Are you able to cut your project down to a minimal reproduction example project and share with us via support@bugsnag.com?

Are you seeing this when building in Android Studio or on the command line (or both)?

If building from the command line can you confirm the gradle version?

**Comment by guilherme-pereira-ifood** [comment] 2020-08-27 11:21
From the command line. Gradle 6.6

**Comment by steve-nester-uk** [comment] 2020-08-28 12:24
@guilherme-pereira-ifood we are continuing to investigate and we're still unable to replicate this issue, would you be able to send across a copy of your app/build.gradle file to support@bugsnag.com please?  Even better, if you could provide a reproduction example as requested above, that would be extremely helpful!  Many thanks!

**Comment by guilherme-pereira-ifood** [comment] 2020-09-10 13:00
@steve-nester-uk sorry for the late reply, I was kinda busy in the past days.

Just sent the `app/build.gradle` to support@bugsnag.com.

**Comment by steve-nester-uk** [comment] 2020-09-10 13:01
Thanks, we'll take a look (I've reopened this issue to continue tracking).

**Comment by ZacSweers** [comment] 2020-09-17 19:24
@guilherme-pereira-ifood do you have something using an older version of okio declared before the bugsnag plugin in your buildscript classpath?

**Comment by guilherme-pereira-ifood** [comment] 2020-09-21 12:57
@ZacSweers no, I don't:

```gradle
buildscript {
  repositories {
    google() {
      content {
        includeGroupByRegex "com\\.android\\..*"
        includeGroupByRegex "com\\.google\\.android\\..*"
        includeGroupByRegex "androidx\\..*"
      }
    }
    jcenter()
    maven { url 'https://maven.google.com' }
    maven { url "https://raw.githubusercontent.com/smilefam/SendBird-SDK-Android/master/" }
    maven { url "https://jitpack.io" }
    maven { url "https://plugins.gradle.org/m2/" }
  }
  dependencies {
    classpath(GradlePlugin.buildTools)
    classpath(GradlePlugin.kotlin)
    classpath(GradlePlugin.googleServices)
    classpath(GradlePlugin.firebasePerformance)
    classpath(GradlePlugin.apkSize)
    classpath(GradlePlugin.bugsnag)
    classpath(GradlePlugin.gradleVersions)
    classpath(GradlePlugin.sonarQube)
    classpath(GradlePlugin.spotless)
    classpath(GradlePlugin.gradleDoctor)
    classpath(GradlePlugin.testRetry)
  }
}
```

**Comment by guilherme-pereira-ifood** [comment] 2020-09-21 16:00
Tried to build release on CI, got the same error.

Tried to use AGP 4.1.0-rc03, same error.

Tried to move bugsnag classpath up, right after `kotlin`.

Checked our Proguard files and the only `okio` reference is this: `-dontwarn okio.**`.

None of these seems to make it work 😢

**Comment by ZacSweers** [comment] 2020-09-21 20:02
`app:dependencies` will give you your app's dependencies but not your buildscript classpath. I suspect a plugin you add to the classpath before bugsnag is using an older version of okio (hard to speculate as your semantic names don't have coordinates). Try adding `classpath("com.squareup.okio:okio:2.8.0")` _before_ any other plugins

**Comment by guilherme-pereira-ifood** [comment] 2020-09-21 21:31
Got it...

I tried adding `classpath("com.squareup.okio:okio:2.8.0")` before any other plugins, but the same error remains.

**Comment by ZacSweers** [comment] 2020-09-21 22:00
Can you link a reproducible project?

**Comment by guilherme-pereira-ifood** [comment] 2020-09-22 12:25
I'm trying to build one, but still can't reproduce. I'll keep trying, but if you have any other idea of where the issue may be, please tell us!

**Comment by guilherme-pereira-ifood** [comment] 2020-09-22 14:31
@ZacSweers @steve-nester-uk I could build a reproducible project: https://github.com/guilherme-pereira-ifood/SampleBugsnag

Build started failing when I added the `buildSrc/build.gradle` with:

```
    implementation "com.squareup.okhttp3:okhttp:$okHttpVersion"
    implementation "com.squareup.moshi:moshi-kotlin:$moshiVersion"
```

**Comment by ZacSweers** [comment] 2020-09-22 16:24
That project still declares the bugsnag plugin last in your buildscript
classpath. Having Moshi and okhttp as regular implementation dependencies
of your project have no bearing on your buildscript classpath either

**Comment by guilherme-pereira-ifood** [comment] 2020-09-22 18:25
Moshi and OkHttp are indeed regular implementation dependencies on my project.

But as I stated, they're also on `buildSrc/build.gradle`, which makes them part of the buildscript classpath, or am I wrong?

Anyway, adding `okio` dependency on `buildSrc/build.gradle` solved the issue. I think it's a good idea to have a troubleshooting topic mentioning this: if you have Moshi declared in a `buildSrc/build.gradle` file, make sure to also have `okio 2.8.0`. 

What do you think?

**Comment by ZacSweers** [comment] 2020-09-22 20:15
The order that you add them on the buildscript classpath is important, it's not like normal project `dependencies {}` blocks where the latest version found wins

**Comment by mattdyoung** [comment] 2020-10-08 08:11
@guilherme-pereira-ifood 
Did you manage to resolve this issue? I can see that your sample project to reproduce the issue https://github.com/guilherme-pereira-ifood/SampleBugsnag is no longer available.

**Comment by guilherme-pereira-ifood** [comment] 2020-10-08 08:18
@mattdyoung yes! I had Moshi on the buildSrc/build.gradle and that caused the issue.

To solve, I had to add Okio (same version bugsnag is using) on buildSrc/build.gradle.

Maybe it's worth adding this (or another solution) on the troubleshooting?

**Comment by mattdyoung** [comment] 2020-10-08 08:27
Thanks @guilherme-pereira-ifood. Yes, we'll look at whether we can improve the documentation to help troubleshoot issues like this.

**Closed by mattdyoung** 2020-10-08 08:27 UTC
Labels: awaiting feedback, bug

**Comment by handstandsam** [comment] 2021-11-19 13:56
Thanks everyone.  I just hit this same issue today and in our `buildSrc/build.gradle.kts` I added `okio` as the first item in the `dependencies` block to resolve it!

```
dependencies {
    // Addresses Bugsnag Class Not Found Issue https://github.com/bugsnag/bugsnag-android-gradle-plugin/issues/280
    implementation("com.squareup.okio:okio:2.10.0")
    
    ...
 }
 ```
